version: "2"

linters:
  enable:
    - depguard
    - gosec
  settings:
    depguard:
      rules:
        all:
          list-mode: strict
          allow:
            - $gostd
            - github.com/grafana/catchpoint-prometheus-exporter
            - github.com/alecthomas/kingpin/v2
            - github.com/prometheus/client_golang
            - github.com/prometheus/common
    gosec:
      severity: medium
      confidence: medium

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/grafana/catchpoint-prometheus-exporter
    gofumpt:
      extra-rules: true
