name: Setup

on:
  workflow_call:

permissions:
  contents: read

jobs:
  setup:
    name: Setup tools and cache dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: 'go.mod'

      - name: Download Go modules
        run: go mod download

      - name: Tools cache
        if: inputs.install-ci-deps
        id: tools-cache
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-tools-${{ hashFiles('Makefile') }}

